# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rule_name', models.CharField(max_length=30)),
                ('Campaigns', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Swiggy'), (1, 'Netflix'), (2, 'Youtube'), (3, 'geeks'), (4, 'music')], max_length=11)),
                ('Schedule', models.TimeField(blank=True, verbose_name='Schedule Time')),
                ('Conditions', models.TextField(blank=True, max_length=100, null=True)),
                ('Action', models.IntegerField(default=1)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
    ]
