# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Action',
            field=models.CharField(choices=[('Notify', 'Notify')], default='Notify', max_length=6),
        ),
        migrations.AlterField(
            model_name='rule',
            name='Status',
            field=models.CharField(choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='Notify', max_length=6),
        ),
    ]
