# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190224_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Status',
            field=models.CharField(choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='Notify', max_length=15),
        ),
    ]
