# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190224_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Schedule',
            field=models.TimeField(blank=True, choices=[(0, 'Every 15 minutes'), (1, 'Every Hour'), (2, 'EveryDay')], verbose_name='Schedule Time'),
        ),
    ]
