# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190226_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Schedule',
            field=models.CharField(choices=[('Fifteen Min', 'Every 15 minutes'), ('Hourly', 'Every Hour'), ('MidDay', 'EveryDay')], max_length=100),
        ),
    ]
