# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 15:23
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190226_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fifteen Min', 'Every 15 minutes'), ('Hourly', 'Every Hour'), ('MidDay', 'EveryDay')], max_length=25),
        ),
    ]
