# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190226_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Schedule',
            field=models.CharField(choices=[('FifteenMin', 'Every 15 minutes'), ('Hour', 'Every Hour'), ('Day', 'EveryDay')], max_length=100),
        ),
    ]
