# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190226_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Conditions',
            field=models.CharField(choices=[('eCPM` >= $5.00 AND `Impressions` >= 1000000', 'eCPM` >= $5.00 AND `Impressions` >= 1000000'), ('Spend` >= $1000.00 AND `eCPC` <=  $0.20', 'Spend` >= $1000.00 AND `eCPC` <=  $0.20'), ('`Clicks` >= 50000 AND `Installs` <= 100', '`Clicks` >= 50000 AND `Installs` <= 100'), ('`eCPI` >= $2.00 AND `Installs` >= 100', '`eCPI` >= $2.00 AND `Installs` >= 100')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rule',
            name='Schedule',
            field=models.CharField(choices=[('Fifteen Min', 'Every 15 minutes'), ('Hourly', 'Every Hour'), ('Mid Day(Noon)', 'EveryDay')], max_length=100),
        ),
    ]
